edu:
  stanford:
    slac:
      mongodb:
        db_admin_uri: ${BASE_LIB_ADMIN_MONGODB_URI:mongodb://admin:admin@localhost:27017/?authSource=admin}

spring:
  data:
    mongodb:
      uri: ${BASE_LIB_MONGODB_URI:mongodb://elogs:elogs@localhost:27017/elogs?authSource=elogs}